### ISSUE TITLE
what should unlimited usage be for usesPerCustomer?

### ISSUE THREAD

**Issue by pinnareet** [thanakijwanavit/villaMasterSchema#122]
https://github.com/thanakijwanavit/villaMasterSchema/blob/4bc78ead571dd7e30941ffa57a2d14ec36582aa6/coupon/coupon2.yaml#L65
<img width="206" alt="Screen Shot 2564-07-23 at 00 36 37" src="https://user-images.githubusercontent.com/4829500/126683667-19f44efc-a377-4c77-807c-1d76df61444a.png">

should it be 0?

**Comment by thanakijwanavit** [comment]
should be none
