### ISSUE TITLE
what is difference between customer type vs customer group ids?

### ISSUE THREAD

**Issue by pathompongbo** [thanakijwanavit/villaMasterSchema#46]
@pinnareet  what is difference between customer type vs customer group ids?
<img width="1207" alt="Screen Shot 2564-05-17 at 14 35 37" src="https://user-images.githubusercontent.com/68332557/118450955-eee7c280-b71e-11eb-99db-cc93a8919619.png">

**Comment by pinnareet** [comment]
customer type is tm_type field (2-digit number) in member-user-database table in dynamodb. 

customer group Ids can be customized in case we want to create custom customer groups. we probably will not implement customer groups now.

**Comment by pinnareet** [comment]
<img width="1384" alt="Screen Shot 2564-05-17 at 15 21 15" src="https://user-images.githubusercontent.com/4829500/118456545-864f1480-b723-11eb-8062-447bd975bfa9.png">
