### ISSUE TITLE
Example coupon set in pieces But the data recorded into the total amount. 

### ISSUE THREAD

**Issue by jirawutch** [thanakijwanavit/villaMasterSchema#47]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/41442346/118453163-1b044300-b721-11eb-874d-d6cb29686a0d.png">

**Comment by pinnareet** [comment]
amount here mean pieces. I will change it to quantity, haha. thank you kaa p aey.

**Comment by pinnareet** [comment]
@jirawutch change _product_ to _productQuantity_ and _amount_ to _quantity_ in commit b461232e4d967871d0f90f9e173e1f8217032336
